### ISSUE TITLE
How to run tests?

### ISSUE THREAD

**Issue by temrix** [robertcorponoi/godot_rust_helper#1]
How can I run the tests? There is no project packaged inside `godot-rust-helper` named `platformer`. If I create an empty project in Godot with this name I get `no such file or directory` from `tests/cli.rs:1426:34`.

**Comment by robertcorponoi** [comment]
The tests currently are made to work with my filesystem since they look for files in specific locations. I will fix that today and get back to you. Thank you for bringing it up.

**Comment by robertcorponoi** [comment]
Sorry for the delay, I've attempted to make it a bit easier by adding a `const` to the `tests/cli.rs` file that let's you specify the directory of godot_rust_helper. This is needed because the tests need to check for specific files and their contents.

Also make sure you follow the instructions in the README, as you have to create a godot project inside of the `tests` directory. This is because the tests create actual instances of godot_rust_helper scripts and it checks to make sure that the files created in the godot project are correct.

If you can think of a better way to run the tests I would be more than glad to implement it.

**Comment by temrix** [comment]
Having to change code on the end-users side is bad practice. Maybe you can refactor that later to use a toml-file or something similar.

Now, if I run the tests I get the following backtrace because on Linux libraries are `.so` (shared objects) and not `.dll`:

```
--- build_library stdout ----
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `false`,
 right: `true`', tests/cli.rs:1371:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: std::panicking::begin_panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:437
   2: cli::build_library
             at /home/temrix/Games/godot_rust_helper/tests/cli.rs:1371
   3: cli::build_library::{{closure}}
             at /home/temrix/Games/godot_rust_helper/tests/cli.rs:1342
   4: core::ops::function::FnOnce::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:227
   5: core::ops::function::FnOnce::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:227
```

**Comment by robertcorponoi** [comment]
There's definitely a lot that still has to be done, this turned from something I was using just for myself into something that I thought could be other use to others.

I'll look into that but if you want to submit a PR I'll be more than glad to look over it.

**Comment by robertcorponoi** [comment]
I've went ahead and fixed the issues outlined here and tested it on both windows and linux. Please let me know if your issue still persists.
