### ISSUE TITLE
Targets are mutually exclusive

### ISSUE THREAD

**Issue by temrix** [robertcorponoi/godot_rust_helper#2]
I have set multiple targets in the file `godot_rust_helper.toml`. When I try to build on Linux, the library is built but not copied.

The logic on line 440 is flawed:

https://github.com/robertcorponoi/godot_rust_helper/blob/c63749c2d289a18c8f86d2448af049a419444735/src/commands.rs#L440

**Comment by robertcorponoi** [comment]
Sorry for not getting to this earlier, I'll look into it but if you want to submit a PR it can get fixed much faster.

**Comment by robertcorponoi** [comment]
So I've looked into this but I'm not sure how the logic is flawed, I just tried it on Linux and it worked so any more detail would be greatly appreciated.

**Comment by temrix** [comment]
I have `windows, linux, osx` as targets. Now if I build the project on Linux, I would expect to build on Linux and if I am on Windows it should build Windows binaries all from the same code base. It is not checking on which system we are currently running. That would be my understanding of the targets.

I guess it is working now, I still need some time to adjust my project and see if it builds.

**Comment by robertcorponoi** [comment]
Ah, I get it now and I think I might know what the issue is, let me take a look at it tomorrow and get back to you with a fix.

Thank you for the extra info and for trying it again. I've decided to take on this project full time instead of just updating it here and there so I'm looking to refactor and fix quite a bit of things.

**Comment by robertcorponoi** [comment]
I've circled back to this and I believe I've fixed the issue with v5.1.1 but it really made me realize the root of the issue. I believe this issue is the config file not being able to be switched between targets without having to rebase which I believe isn't very intuitive so I'll be working on that next.

**Comment by temrix** [comment]
I just saw a few days back that you wrote over 5000 LOC of tests. This is more than I possibly could have ever asked of you. Thanks for making such an effort!

When I find something again I will try making a pull request and an issue.

**Comment by robertcorponoi** [comment]
I'm currently working on re-writing this so any other suggestions that might make things easier to use would be very appreciated.

**Comment by temrix** [comment]
This issue can be closed now as far as I'm concerned.
